# Generated by Django 4.2.7 on 2026-09-07 09:32

import apps.notes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_badge_text_course_career_opportunities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='notes/bundles/')),
                ('price', models.DecimalField(decimal_places=2, default=799.0, max_digits=8)),
                ('original_price', models.DecimalField(decimal_places=2, default=1499.0, max_digits=8)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notes Bundle',
                'verbose_name_plural': 'Notes Bundles',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Complete Comprehensive Guide & Interview Kit', max_length=250)),
                ('short_description', models.CharField(help_text='Catchy 1-2 sentence overview for cards', max_length=350)),
                ('full_description', models.TextField(help_text='Detailed overview, table of contents summary, audience, and key highlights')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='notes/covers/')),
                ('author_name', models.CharField(default='TECHSPIRE Expert Academic Council', max_length=120)),
                ('version', models.CharField(default='v2.0 (2026 Edition)', max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('estimated_reading_hours', models.DecimalField(decimal_places=1, default=12.0, max_digits=5)),
                ('page_count_est', models.PositiveIntegerField(default=150, help_text='Estimated textbook page count')),
                ('exercise_count', models.PositiveIntegerField(default=25)),
                ('project_count', models.PositiveIntegerField(default=5)),
                ('interview_q_count', models.PositiveIntegerField(default=40)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=299.0, help_text='Selling price in INR', max_digits=8)),
                ('original_price', models.DecimalField(decimal_places=2, default=599.0, help_text='Original printed edition / MRP in INR', max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('pdf_file', models.FileField(blank=True, help_text='Uploaded pre-compiled PDF or generated asset', null=True, upload_to='notes/pdfs/')),
                ('what_you_will_learn', models.TextField(blank=True, help_text='Key takeaways separated by newlines')),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisites separated by newlines')),
                ('target_audience', models.TextField(blank=True, help_text='Target audience separated by newlines')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_products', to='courses.coursecategory')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_products', to='courses.course')),
            ],
            options={
                'verbose_name': 'Notes Product',
                'verbose_name_plural': 'Notes Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=apps.notes.models.generate_order_id, max_length=60, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid & Active'), ('failed', 'Payment Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_method', models.CharField(default='UPI / Card / NetBanking', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='notes.notesbundle')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='notes.notesproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notes Order',
                'verbose_name_plural': 'Notes Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotesChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('order', models.PositiveIntegerField(default=1)),
                ('summary', models.CharField(blank=True, max_length=350)),
                ('is_preview', models.BooleanField(default=False, help_text='Allow free sample preview to non-buyers')),
                ('read_time_mins', models.PositiveIntegerField(default=20)),
                ('content_markdown', models.TextField(help_text='Comprehensive structured study notes in Markdown/HTML')),
                ('key_takeaways', models.TextField(blank=True, help_text='Key takeaways separated by newlines')),
                ('interview_tips', models.TextField(blank=True, help_text='Interview tips and expected technical questions')),
                ('practice_exercise', models.TextField(blank=True, help_text='Hands-on practice challenge')),
                ('exercise_solution', models.TextField(blank=True, help_text='Solution and explanation')),
                ('downloadable_asset', models.FileField(blank=True, null=True, upload_to='notes/resources/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='notes.notesproduct')),
            ],
            options={
                'verbose_name': 'Notes Chapter',
                'verbose_name_plural': 'Notes Chapters',
                'ordering': ['order', 'id'],
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.AddField(
            model_name='notesbundle',
            name='products',
            field=models.ManyToManyField(related_name='bundles', to='notes.notesproduct'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount (%)'), ('fixed', 'Fixed Discount (₹)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='e.g. 20 for 20% or 100 for ₹100', max_digits=6)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1000)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='notes.notesproduct')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='NotesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='notes.notesproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notes Review',
                'verbose_name_plural': 'Notes Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='NotesReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('completed_chapters', models.ManyToManyField(blank=True, related_name='completed_by_users', to='notes.noteschapter')),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.noteschapter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_records', to='notes.notesproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Progress',
                'verbose_name_plural': 'Reading Progress Records',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='NotesBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='notes.noteschapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notes Bookmark',
                'verbose_name_plural': 'Notes Bookmarks',
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
