version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: techspire_postgres
    restart: always
    environment:
      POSTGRES_DB: techspire_db
      POSTGRES_USER: techspire_user
      POSTGRES_PASSWORD: techspire_secure_password_2026
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: techspire_web
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_techspire_data &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 techspire_project.wsgi:application"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=production-django-key-techspire-learning-2026
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://techspire_user:techspire_secure_password_2026@db:5432/techspire_db
    depends_on:
      - db

volumes:
  postgres_data:
  media_volume:
  static_volume:
