# Generated by Django 4.2.7 on 2026-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('courses', 'Courses & Learning'), ('certificates', 'Certificates & Verification'), ('enrollment', 'Enrollment & Access')], default='general', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='TECHSPIRE Learning', max_length=100)),
                ('tagline', models.CharField(default='Learn Today, Lead Tomorrow.', max_length=200)),
                ('business_name', models.CharField(default='TECHSPIRE', max_length=100)),
                ('proprietor_name', models.CharField(default='Vivek Jat', max_length=100)),
                ('business_type', models.CharField(default='Proprietorship / Micro Enterprise', max_length=100)),
                ('location', models.CharField(default='Indore, Madhya Pradesh, India', max_length=100)),
                ('address', models.TextField(default='53/43 Radhaswami Nagar, Nowlakha, Indore, Madhya Pradesh 452001')),
                ('email', models.EmailField(default='vivekjat301@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 9713931301', max_length=20)),
                ('udyam_registration', models.CharField(default='UDYAM-MP-23-0283495', max_length=50)),
                ('gstin', models.CharField(default='23BEZPJ5728J1ZW', max_length=50)),
                ('hero_title', models.CharField(default='Master In-Demand Tech Skills & Build Your Future', max_length=200)),
                ('hero_subtitle', models.TextField(default='Industry-aligned hands-on courses in Web Development, Python, AI Tools, and Data Analytics. Earn verified certificates recognized by top employers.')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Python Developer at Tech Corp', max_length=100)),
                ('course_taken', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
