# Generated by Django 4.2.7 on 2026-09-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge_text',
            field=models.CharField(blank=True, default='Verified Certificate', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='career_opportunities',
            field=models.TextField(blank=True, help_text='Target job roles / opportunities (newline separated)'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='roadmap_highlights',
            field=models.TextField(blank=True, help_text='Course learning journey milestones (newline separated)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='diagram_code',
            field=models.TextField(blank=True, help_text='Mermaid / SVG / ASCII visual diagram code'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise_solution',
            field=models.TextField(blank=True, help_text='Self-check solution or explanation for the exercise'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='interview_tips',
            field=models.TextField(blank=True, help_text='Technical interview tip or common interview questions on this topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='key_takeaways',
            field=models.TextField(blank=True, help_text='Core takeaway bullet points (newline separated)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes_markdown',
            field=models.TextField(blank=True, help_text='Comprehensive rich educational study notes with formatting, code, and callouts'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='practice_exercise',
            field=models.TextField(blank=True, help_text='Hands-on coding exercise / assignment challenge'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_title',
            field=models.CharField(blank=True, default='Study Material & Notes', help_text='Name of downloadable asset', max_length=150),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Summary text or brief overview'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('article', 'Reading & Notes Tutorial'), ('exercise', 'Practical Hands-on Lab'), ('quiz', 'Module Quiz / Assessment')], default='article', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(help_text='Clear, comprehensive model answer with examples')),
                ('category_tag', models.CharField(default='Core Concepts', help_text='e.g. ORM, Architecture, DAX, Algorithms', max_length=100)),
                ('difficulty', models.CharField(choices=[('basic', 'Fundamental / Fresher'), ('intermediate', 'Intermediate / 1-3 Yrs'), ('advanced', 'Advanced / Senior')], default='intermediate', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('short_description', models.CharField(help_text='Short teaser of the project goals', max_length=300)),
                ('description', models.TextField(help_text='Detailed project requirements, user stories, and architecture')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner Level'), ('intermediate', 'Intermediate Level'), ('advanced', 'Advanced Capstone')], default='intermediate', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('technologies_used', models.CharField(default='Python, Django, PostgreSQL, HTML/CSS', help_text='Comma-separated tech stack', max_length=250)),
                ('github_starter_url', models.CharField(blank=True, help_text='GitHub starter template or repository link', max_length=300)),
                ('submission_instructions', models.TextField(blank=True, help_text='Deliverables checklist and evaluation criteria')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Project',
                'verbose_name_plural': 'Course Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='Assignment prompt, tasks to perform, expected output')),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='courses.module')),
            ],
            options={
                'verbose_name': 'Course Assignment',
                'verbose_name_plural': 'Course Assignments',
                'ordering': ['order', 'id'],
            },
        ),
    ]
